name: Bug Report
description: Report a bug or documentation issue with RTI Connector for Rust
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below to help us understand and reproduce the issue.

  - type: input
    id: connector-version
    attributes:
      label: Connector Version
      description: Which version of RTI Connector for Rust are you using?
      placeholder: e.g., 1.5.0, or commit hash
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: reproducer
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue, including minimal code examples if possible
      placeholder: |
        1. Create a Connector with...
        2. Call method...
        3. Observe error...

        ```rust
        // Minimal code example
        ```

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: If applicable, paste any error messages, stack traces, or relevant log output
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the issue here (e.g., XML configuration, build.rs output, environment variables, platform details, etc.)
      placeholder: Any additional information that might help...
