name: Question
description: Ask a question about RTI Connector for Rust
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: How do I... / What's the best way to... / Can RTI Connector...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional context, code samples, configuration, or environment info that might be helpful
      placeholder: Any additional information that might help...
